apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prod-seatyrants-worldserver-publictest
  namespace: prod-seatyrants-worldserver-publictest
spec:
  replicas: 22 # Nombre de maps dans SeaTyrants
  serviceName: prod-seatyrants-worldserver-service-publictest
  selector:
    matchLabels:
      app: prod-seatyrants-worldserver-publictest
  template:
    metadata:
      labels:
        app: prod-seatyrants-worldserver-publictest
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: prod-seatyrants-worldserver-publictest
          image: corentin35/seatyrants-worldserver:${TAG_VERSION}
          imagePullPolicy: Always
          ports:
            - containerPort: 4001
              name: udp
              protocol: UDP
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
