apiVersion: v1
kind: Service
metadata:
  name: staging-seatyrants-worldserver-service-privatetest
  namespace: staging-seatyrants-worldserver-privatetest
spec:
  clusterIP: None  # Headless service
  selector:
    app: staging-seatyrants-worldserver-privatetest
  ports:
    - name: udp
      port: 4001
      targetPort: 4001
      protocol: UDP
