name: Generate Executable Server - Production

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: write
  discussions: write

jobs:
  build_server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      # Ajouter ici pour build l'image docker et envoyé au cluster..etc