name: Generate Executable Server - Staging

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build_server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      # Ajouter ici pour build l'image docker et envoyé au cluster..etc