name: Generate Executable Server - Production

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: write
  discussions: write

env:
  XCODE_VERSION: "26.3.0"

jobs:
  build_server:
    strategy:
      fail-fast: false
      matrix:
        config:
        - { runner: ubuntu-22.04,     platform: linux,    arch: x64 }
    name: ${{ matrix.config.platform }}-${{ matrix.config.arch }}-${{ matrix.config.sdk }}
    runs-on: ${{ matrix.config.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Get dependencies with CMake - All platforms
        run: cmake -P cmake/setup_dependencies.cmake

      - name: Setup Xcode and Setup Command Line Tools - macOS / iOS
        if: matrix.config.platform == 'macos'
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Determine SDK Path and set SDKROOT - macOS / iOS
        if: matrix.config.platform == 'macos'
        run: |
          sdk="${{ matrix.config.sdk }}"
          SDKROOT=$(xcrun --sdk "$sdk" --show-sdk-path)
          SDKVERSION=$(xcrun --sdk "$sdk" --show-sdk-version)
          echo "SDKROOT=$SDKROOT" >> $GITHUB_ENV
          echo "Using SDK: $sdk"
          echo "SDK Path: $SDKROOT"
          echo "SDK Version: $SDKVERSION"
        shell: bash

      - name: Install dev dependencies (for SDL3) - Linux (x64)
        if: matrix.config.platform == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get -y install build-essential git make \
          pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev \
          libaudio-dev libfribidi-dev libjack-dev libsndio-dev libx11-dev libxext-dev \
          libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev \
          libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
          libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev libthai-dev \
          libpipewire-0.3-dev libwayland-dev libdecor-0-dev liburing-dev

      - name: Configure project with CMake and Run build - Linux (x64)
        if: matrix.config.platform == 'linux'
        uses: threeal/cmake-action@v2.1.0
        with:
          run-build: true
          build-dir: build-${{ matrix.config.platform }}-${{ matrix.config.arch }}
          generator: Unix Makefiles
          c-compiler: gcc
          cxx-compiler: g++
          options: CMAKE_BUILD_TYPE=Release SERVER_ENV=staging