name: Generate Executable Server - Staging

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build_server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./docker/staging/Dockerfile
          push: true
          tags: corentin35/rcnet-server-template:staging-${{ github.sha }}

      - name: Replace image tag in fleet.yaml for Kubernetes
        run: |
          sed -i 's/\${TAG_VERSION}/'${{ github.sha }}'/g' k8s/staging/fleet.yaml

      - name: Connect to the cluster K3S for deploy
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG_CLUSTER_STAGING_CRZGAMES_BASE64 }}
        with:
          args: |
            apply -f k8s/staging/fleet.yaml